- name: setup directories
  file: 
    path: "/opt/45drives/containers/nextcloud/nginx/{{item}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  with_items: ["modsec-confs", "html", "modsec-crs-confs", "server-confs"]

- name: set dir permissions 
  file:
    path: "/opt/45drives/containers/nextcloud/nginx/certs"
    owner: 101
    group: 101
    mode: 0755
    recurse: yes
    state: directory

- name: move modsec-conf template
  template: 
    src: nextcloudmodsec.conf.j2
    dest: /opt/45drives/containers/nextcloud/nginx/modsec-confs/nextcloud.conf
    owner: root

- name: move modsec-crs-conf template
  copy: 
    src: nextcloudmodseccrs.conf
    dest: /opt/45drives/containers/nextcloud/nginx/modsec-crs-confs/nextcloud.conf

- name: move server-confs template
  copy: 
    src: nextcloudserver.conf
    dest: /opt/45drives/containers/nextcloud/nginx/server-confs/nextcloud.conf