- name: setup directories
  file: 
    path: "/containers/nextcloud/nginx/{{item}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  with_items: ["modsec-configs", "html", "modsec-crs-confs", "server-confs"]

- name: set dir permissions 
  file: "/containers/nextcloud/nginx/certs"
  owner: 101
  group: 101
  mode: 0755
  state: directory

- name: move modsec-conf template
  template: 
    src: nextcloudmodsec.conf
    dest: ~/containers/nextcloud/nginx/modsec-confs/nextcloud.conf
    owner: root

- name: move modsec-crs-conf template
  template: 
    src: nextcloudmdseccrs.conf
    dest: ~/containers/nextcloud/nginx/modsec-crs-confs/nextcloud.conf

- name: move server-confs template
  template: 
    src: nextcloudserver.conf
    dest: ~/containers/nextcloud/nginx/server-confs/nextcloud.conf