---
- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: container-engine

- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: nextcloud