---
- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: nextcloud

- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: nginx

- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: run-containers
