- name: setup directories
  file: 
    path: "/opt/45drives/containers/nextcloud/{{item}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  with_items: ["db", "nginx", "html"]

- name: make building directories
  file:
    path: "/opt/45drives/nextcloud"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: move Dockerfile template
  copy: 
    src: Dockerfile
    dest: /opt/45drives/nextcloud/Dockerfile
    owner: root

- name: build podman container
  containers.podman.podman_image:
    name: 45cloud
    path: /opt/45drives/nextcloud