- name: setup directories
  file: 
    path: "/containers/nextcloud/{{item}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  with_items: ["db", "nginx", "html"]

- name: make building directorie
  file:
    path: "/opt/nextcloud"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: move Dockerfile template
  template: 
    src: Dockerfile
    dest: /opt/nextcloud/Dockerfile
    owner: root