---
- name: Create pod
  include_tasks: podman-pod.yml

- name: Standup MariaDB 
  include_tasks: mariadb.yml

- name: standup nextcloud
  include_tasks: nextcloud.yml

- name: standup nginx
  include_tasks: nginx.yml

- name: setup systemd
  include_tasks: generate-systemd.yml
  