- name: pull mariaDB image
  containers.podman.podman_image:
    name: docker.io/library/mariadb
    pull: true
    tag: latest

- name: start mariaDB container
  containers.podman.podman_container:
    name: mariadb
    pod: nextcloud_pod
    image: docker.io/library/mariadb:latest
    state: started
    volume:
      - /opt/45drives/containers/nextcloud/db:/var/lib/mysql:Z
    env: 
       MYSQL_USER: '{{ sql_user }}'
       MYSQL_PASSWORD: '{{ sql_password }}'
       MYSQL_ROOT_PASSWORD: '{{ sql_root_password }}'
       MYSQL_DATABASE: '{{ sql_database }}'

    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      time: 120
      names: true