- name: start nextcloud container
  containers.podman.podman_container: 
    name: nextcloud
    pod: nextcloud_pod
    image: localhost/45cloud
    state: started
    volume:
      - /opt/45drives/containers/nextcloud/html:/var/www/html:z
    env: 
       MYSQL_HOST: "127.0.0.1"
       MYSQL_USER: "nextcloud"
       MYSQL_PASSWORD: "sql-password"
       MYSQL_DATABASE: "nextcloud"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      time: 120
      names: true