- name: create nextcloud pod 
  containers.podman.podman_pod: 
    name: nextcloud_pod
    state: started
    ports:
     - "8080:8080"
     - "8443:8443"

    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      time: 120
      names: true